
package clt.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FanServerWSService", targetNamespace = "http://fanserverinfo/", wsdlLocation = "http://localhost:7070/FanZoneServerWS?wsdl")
public class FanServerWSService
    extends Service
{

    private final static URL FANSERVERWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(clt.ws.FanServerWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = clt.ws.FanServerWSService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7070/FanZoneServerWS?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7070/FanZoneServerWS?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FANSERVERWSSERVICE_WSDL_LOCATION = url;
    }

    public FanServerWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FanServerWSService() {
        super(FANSERVERWSSERVICE_WSDL_LOCATION, new QName("http://fanserverinfo/", "FanServerWSService"));
    }

    /**
     * 
     * @return
     *     returns FanServerWS
     */
    @WebEndpoint(name = "FanServerWSPort")
    public FanServerWS getFanServerWSPort() {
        return super.getPort(new QName("http://fanserverinfo/", "FanServerWSPort"), FanServerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FanServerWS
     */
    @WebEndpoint(name = "FanServerWSPort")
    public FanServerWS getFanServerWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fanserverinfo/", "FanServerWSPort"), FanServerWS.class, features);
    }

}
